version: "3.8"

services:
  db:
    image: postgres:15
    container_name: Project-Leave-System
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: leave-system
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local